### PR TITLE
fix: group MultiAsset entries by policyId before merging in parseToke…

### LINKED ISSUE #582: Multiple native assets with different policy IDs parsing failure
### Context & versions
- **Rosetta Java Implementation**: checked on v1.3.2, probably affects other previous versions too
- **Network**: preprod
- **Test Location**: `/tests/integration/golden_examples/rosetta_java/construction/parse/native_assets/multiple_assets_different_policies.json`

### Steps to reproduce
1. Start rosetta-java API
2. Send a `/construction/parse` request with a transaction containing multiple native assets with different policy IDs
### Request Example

```json
{
  "network_identifier": {
    "blockchain": "cardano",
    "network": "preprod"
  },
  "signed": false,
  "transaction": "8279020e61343030643930313032383138323538323034663235666438636361383335616632316633616333373562616336303166393765616437356632653739313433626466373166653263346265303433653866303030313831383235383339303038663037356362646632643164376633346166396131613662323736643834636437623439396338306361663632313764313163366630303366316232616535623432633964663465346134353862626639646230616637663731633436333662643833376231313062613437383032383231613030333564363066613335383163363832666536306339393138383432623333323363343362353134346263336435326132336264326662383133343535363064373366363361313438343736663663363434333666363936653139303132633538316338343965366562383436353336323665623830306262326663666539356334643562613966386633303631643939373336313462653233346131353134353731373536393665363534383666373237333635333033303334333033313330313930326565353831636636366437386234613363623364333761666130656333363436316535316563626465303066323663386630613638663934623639383830613134613464373935343666366236353665333033303331313930376430303231613030303733326631303331613035666363666432a16a6f7065726174696f6e7382a6746f7065726174696f6e5f6964656e746966696572a165696e64657800676163636f756e74a16761646472657373786c616464725f7465737431717a38737768396137746761307536326c78733664766e6b6d707864306479656571783237637368367977783771706c72763477746470766e68367766667a63683075616b7a68683775777976643461736461337a7a61793071707163706c77683066616d6f756e74a26863757272656e6379a26673796d626f6c6341444168646563696d616c73066576616c7565682d343030303030306b636f696e5f6368616e6765a26f636f696e5f6964656e746966696572a16a6964656e7469666965727842346632356664386363613833356166323166336163333735626163363031663937656164373566326537393134336264663731666532633462653034336538663a306b636f696e5f616374696f6e6a636f696e5f7370656e74686d65746164617461a16b746f6b656e42756e646c6583a266746f6b656e7381a166616d6f756e74a26863757272656e6379a26673796d626f6c78223435373137353639366536353438366637323733363533303330333433303331333068646563696d616c73006576616c75656337353068706f6c696379496478383834396536656238343635333632366562383030626232666366653935633464356261396638663330363164393937333631346265323334a266746f6b656e7381a166616d6f756e74a26863757272656e6379a26673796d626f6c74346437393534366636623635366533303330333168646563696d616c73006576616c7565643230303068706f6c696379496478386636366437386234613363623364333761666130656333363436316535316563626465303066323663386630613638663934623639383830a266746f6b656e7381a166616d6f756e74a26863757272656e6379a26673796d626f6c703437366636633634343336663639366568646563696d616c73006576616c75656333303068706f6c696379496478383638326665363063393931383834326233333233633433623531343462633364353261323362643266623831333435353630643733663633647479706565696e707574a5746f7065726174696f6e5f6964656e746966696572a165696e64657801676163636f756e74a16761646472657373786c616464725f7465737431717a38737768396137746761307536326c78733664766e6b6d707864306479656571783237637368367977783771706c72763477746470766e68367766667a63683075616b7a68683775777976643461736461337a7a61793071707163706c77683066616d6f756e74a26863757272656e6379a26673796d626f6c6341444168646563696d616c73066576616c75656733353238323037686d65746164617461a16b746f6b656e42756e646c6583a266746f6b656e7381a166616d6f756e74a26863757272656e6379a26673796d626f6c78223435373137353639366536353438366637323733363533303330333433303331333068646563696d616c73006576616c75656337353068706f6c696379496478383834396536656238343635333632366562383030626232666366653935633464356261396638663330363164393937333631346265323334a266746f6b656e7381a166616d6f756e74a26863757272656e6379a26673796d626f6c74346437393534366636623635366533303330333168646563696d616c73006576616c7565643230303068706f6c696379496478386636366437386234613363623364333761666130656333363436316535316563626465303066323663386630613638663934623639383830a266746f6b656e7381a166616d6f756e74a26863757272656e6379a26673796d626f6c703437366636633634343336663639366568646563696d616c73006576616c75656333303068706f6c6963794964783836383266653630633939313838343262333332336334336235313434626333643532613233626432666238313334353536306437336636336474797065666f7574707574"
}
```

#### cardano-rosetta-java
```json
{
  "code": 5000,
  "message": "An error occurred",
  "retriable": true,
  "details": {
    "message": "An error occurred for request 31426: Trying to add MultiAssets with different policyId"
  }
}
```
**HTTP Status**: 500

#### TypeScript implementation
```json
{
  "code": 5000,
  "message": "An error occurred",
  "retriable": true,
  "details": {
    "message": "An error occurred for request 1577: \"value\" is required!"
  }
}
```
**HTTP Status**: 500

### Expected behavior

The parse endpoint should successfully parse the transaction and return:

```json
{
  "operations": [
    {
      "operation_identifier": {"index": 0},
      "type": "input",
      "account": {"address": "addr_test1qz8swh9a7tga0u62lxs6dvnkmpxd0dyeeqx27csh6ywx7qplrv4wtdpvnh6wffzch0uakzhh7uwyvd4asda3zzay0qpqcplwh0"},
      "amount": {
        "value": "-4000000",
        "currency": {"symbol": "ADA", "decimals": 6}
      },
      "coin_change": {
        "coin_identifier": {"identifier": "4f25fd8cca835af21f3ac375bac601f97ead75f2e79143bdf71fe2c4be043e8f:0"},
        "coin_action": "coin_spent"
      },
      "metadata": {
        "tokenBundle": [
          {
            "policyId": "849e6eb8465362eb800bb2fcfe95c4d5ba9f8f3061d9973614be234",
            "tokens": [{"value": "750", "currency": {"symbol": "4571756e65486f727365303034303130", "decimals": 0}}]
          },
          {
            "policyId": "f66d78b4a3cb3d37afa0ec36461e51ecbde00f26c8f0a68f94b69880",
            "tokens": [{"value": "2000", "currency": {"symbol": "4d79546f6b656e303031", "decimals": 0}}]
          },
          {
            "policyId": "682fe60c9918842b3323c43b5144bc3d52a23bd2fb8134556d73f63",
            "tokens": [{"value": "300", "currency": {"symbol": "476f6c64436f696e65", "decimals": 0}}]
          }
        ]
      }
    },
    {
      "operation_identifier": {"index": 1},
      "type": "output",
      "account": {"address": "addr_test1qz8swh9a7tga0u62lxs6dvnkmpxd0dyeeqx27csh6ywx7qplrv4wtdpvnh6wffzch0uakzhh7uwyvd4asda3zzay0qpqcplwh0"},
      "amount": {
        "value": "3528207",
        "currency": {"symbol": "ADA", "decimals": 6}
      },
      "metadata": {
        "tokenBundle": [
          {
            "policyId": "849e6eb8465362eb800bb2fcfe95c4d5ba9f8f3061d9973614be234",
            "tokens": [{"value": "750", "currency": {"symbol": "4571756e65486f727365303034303130", "decimals": 0}}]
          },
          {
            "policyId": "f66d78b4a3cb3d37afa0ec36461e51ecbde00f26c8f0a68f94b69880",
            "tokens": [{"value": "2000", "currency": {"symbol": "4d79546f6b656e303031", "decimals": 0}}]
          },
          {
            "policyId": "682fe60c9918842b3323c43b5144bc3d52a23bd2fb8134556d73f63",
            "tokens": [{"value": "300", "currency": {"symbol": "476f6c64436f696e65", "decimals": 0}}]
          }
        ]
      }
    }
  ],
  "account_identifier_signers": [
    {"address": "addr_test1qz8swh9a7tga0u62lxs6dvnkmpxd0dyeeqx27csh6ywx7qplrv4wtdpvnh6wffzch0uakzhh7uwyvd4asda3zzay0qpqcplwh0"}
  ]
}
```

### PR DESCRIPTION
**Pull request by ghost**
## Summary

  Fixes #582 — `/construction/parse` returned HTTP 500 when a transaction output contained native assets from
  multiple distinct policy IDs.

  ## Root Cause

  `ParseConstructionUtil.parseTokenAsset()` received the **full** `multiAssets` list on every call and attempted
   to merge all entries using `MultiAsset.plus()`, regardless of policy ID. The `policyId` parameter was passed
  in but never used during the merge. When entries with different policy IDs were present, `plus()` threw:

  "Trying to add MultiAssets with different policyId"

  ```java
  // BEFORE — merges the entire list unconditionally
  MultiAsset mergedMultiAssets = multiAssets.getFirst();
  for (int i = 1; i < multiAssets.size(); i++) {
      mergedMultiAssets.plus(multiAssets.get(i));  // throws on different policyId
  }
  ```

  Fix

  Group MultiAsset entries by policyId before merging so that plus() is only ever called within entries sharing
  the same policy.
```java
  // AFTER — group by policy first, then merge within each group
  Map<String, List<MultiAsset>> byPolicy = multiAssets.stream()
          .collect(Collectors.groupingBy(MultiAsset::getPolicyId));

  List<TokenBundleItem> tokenBundle = byPolicy.entrySet().stream()
          .map(entry -> parseTokenAsset(entry.getValue(), entry.getKey()))
          .sorted(Comparator.comparing(TokenBundleItem::getPolicyId))
          .toList();
```
 ` parseTokenAsset` now receives only same-policy entries (samePolicyAssets), making the existing merge loop safe.

### CODE REVIEW

File: api/src/main/java/org/cardanofoundation/rosetta/common/util/ParseConstructionUtil.java [hunk 1]
```diff
@@ -116,20 +118,23 @@ public static List<OperationIdentifier> getRelatedOperationsFromInputs(List<Oper
...
-        if (!ObjectUtils.isEmpty(multiAssets)) {
-            log.info("[parseTokenBundle] About to parse {} multiAssets from token bundle",
-                    multiAssets.size());
-
-            tokenBundle = multiAssets.stream()
-                    .map(key -> parseTokenAsset(multiAssets, key.getPolicyId()))
-                    .sorted(Comparator.comparing(TokenBundleItem::getPolicyId))
-                    .toList();
+        if (ObjectUtils.isEmpty(multiAssets)) {
+            return null;
```
Comment (matiwinnetou) [inline api/src/main/java/org/cardanofoundation/rosetta/common/util/ParseConstructionUtil.java:125]: should return "@Nullable" in the function signature.

**Comment by matiwinnetou** [comment]
@linconvidal integration tests on this one please in python, thank you including regression testing.

File: api/src/main/java/org/cardanofoundation/rosetta/common/util/ParseConstructionUtil.java (hunk 1 above)
Comment (matiwinnetou) [reply api/src/main/java/org/cardanofoundation/rosetta/common/util/ParseConstructionUtil.java:125]: alternatively we could do "Optional" on the function signature.

Comment (ghost) [reply api/src/main/java/org/cardanofoundation/rosetta/common/util/ParseConstructionUtil.java:125]: added "@nullable"

**Review by matiwinnetou — APPROVED** [review]
